### ISSUE TITLE
Missing sensors ...

### ISSUE THREAD

**Issue by frayberen** [kalanda/homeassistant-aemet-sensor#17]
Hello, suddenly all the sensors from two different locations that I had configured have disappeared. Any indication?

**Comment by kalanda** [comment]
Sorry, I can't help you if you don't tell me more about your issue.

**Comment by kzim200** [comment]
I have noticed the same problem in my home assistant.
All of my aemet sensors disappeared a few days ago.
I have reinstalled via hacs and see this in the logs:

Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/aemet/AemetApi/__init__.py:74
Integration: Sensor (documentation, issues)
First occurred: 3:01:40 PM (1 occurrences)
Last logged: 3:01:40 PM

Error while setting up aemet platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.aemet.es', port=443): Max retries exceeded with url: /opendata/api/observacion/convencional/datos/estacion/1387?api_key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJremltbTIwMEBnbWFpbC5jb20iLCJqdGkiOiJhMDA5OTFjNy1mYjBkLTRhOTktYTMzYS02ZmJlZjdlZmM0NDIiLCJpc3MiOiJBRU1FVCIsImlhdCI6MTU5NTU4MzcxNCwidXNlcklkIjoiYTAwOTkxYzctZmIwZC00YTk5LWEzM2EtNmZiZWY3ZWZjNDQyIiwicm9sZSI6IiJ9.BhimEXapfbIky2YMdsaFwK_XkeKBPrcf9PP-7bQjpbU (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aemet/sensor.py", line 77, in setup_platform
    aemetApi.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/AemetApi/__init__.py", line 74, in update
    main_rsp = requests.get(endpoint_url, params=params)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='opendata.aemet.es', port=443): Max retries exceeded with url: /opendata/api/observacion/convencional/datos/estacion/mystationid?api_key=My API KEY (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

**Comment by kalanda** [comment]
@frayberen and @kzim200 the issue was caused by some change in the SSL certificate of AEMET. Seems like this days they changed their certificate to a self signed instead of signed by a trusted certification authority.

![Captura de pantalla 2020-07-24 a las 19 44 39](https://user-images.githubusercontent.com/392687/88420968-0187b880-cde8-11ea-8cd2-6f9ae1e85da4.png)

So, I made some changes to avoid verification when the API is requested. This means that some messages such as `InsecureRequestWarning: Unverified HTTPS request is being made to host 'opendata.aemet.es'. Adding certificate verification is strongly advised.`are going to start appearing in the logs, but, there is the best way to avoid issues.

You can just update is using HACS or download the new release here.
https://github.com/kalanda/homeassistant-aemet-sensor/releases/tag/v1.3.0

Regards,

**Comment by kzim200** [comment]
That fixed it for me.

Thank you.

**Comment by frayberen** [comment]
Fixed issue after upgrade.

Thank you very much!!
